language: node_js
node_js:
- node
notifications:
  slack:
    secure: E6aW1jFzaA4cLjCJhMzu9ioqVp01SzrbtjBeXh08qYiUNAQcWShkFzqxMDH1qLDXggk1iwsKgyLWoCG0xT1Ku58hhmayFpyuIe+ExcZzz2ZeJThI/0uW6O8qv02F2gy++G+/elPEjbIXKpo+rbAiBFFtE3NnuT/I6askD9v6uoQu4p8eSGsWWGYvoKYUq1GL2gTXOcUE9joP1Uj3I23eLe/pnQAFES3Vl2dG8pybg5ytmVkkguMBpcrUIXHGOQN74OiMNXB1u7CPxIlwGy2e04nF3GUYEv1h0urYWgi2J+MsIlGRIJM/dFgqxexjlH1PXwmw/e1uIxBIxY8MLOlvRyEyhfCczXdwy/hrFvue3fFgW/sJMeZPsZsSW5mbf+7MEtNoxQVVqzB7izdH+MEmHWsa5aa5lVJI5s69y7I1HLLNjCwYgZWI5SyxiTHZEC7xiVRqYBI7gymCAotEz2Qnj9+S8++CAfTy+ALh3Lqc8d26w+hALwkxh6PH2dVcwQEt58rhTdRREc4/6iPj+7E6/w6f9PBdayM5xaHSGF9M+53PJMOp03ws8Lf73BibrhJln9aYBhJmJlPrf/wgc+ZyjCaQQ5IsmqjadN6pXLj7apGQcXL1q3VAuM3HjExaFCziKFUyHXnNd7RTy6J7OlpkgsRiNLPrxszmUJwfrctx/5k=
